### ISSUE TITLE
None of the download links work 

### ISSUE THREAD

**Issue by jimoquinn** [NaomiProject/naomi-website#19]
Not sure what happened, but none of the download links work.

**Comment by AustinCasteel** [comment]
If you could be more precises on what and where exactly, that would help a lot.

Both of the manual instructions "bintray curl" for stable and dev work. (The main GH repo works as a backup as well) However if you are referring to the Naobian download, it is still in development. It was supposed to be done a good while ago but it has been pushed back multiple times due to difficulties, I apologize for the inconvenience.

**Comment by jimoquinn** [comment]
Thanks for the quick response and keep up the good work.  If I visit the main website (https://projectnaomi.com) and click the big red download button on the bottom of the page which takes me here (https://projectnaomi.com/download/).  

Then under "Install Naobian (Recommended)" on step #2, the link doesn't work.

2.  Download the Naobian image (.img file) for your system from https://github.com/naomiproject/naobian/releases/latest:

I get a 404 error from the github site.  I'll give the "curl" instructions a shot.

**Comment by AustinCasteel** [comment]
Closing; issue handled in [PR#23](https://github.com/NaomiProject/naomi-website/pull/23). If issue arises again this can be reopened or a new issue can be made.
